apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRvcHMyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJnaXRvcHMyIiwicGFzc3dvcmQiOiJPZ2hBWXBTTDN0dzBTVjRIcFI3MlBpVTZha3NILzBPNiIsImF1dGgiOiJaMmwwYjNCek1qcFBaMmhCV1hCVFRETjBkekJUVmpSSWNGSTNNbEJwVlRaaGEzTklMekJQTmc9PSJ9fX0=
kind: Secret
metadata:
  name: acr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson