apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: default
  labels:
    app: spring
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
      env: dev
  template:
    metadata:
      labels:
        app: spring
        env: dev
    spec:
      containers:
      - name: spring
        image: gitops2.azurecr.io/spring-boot-thymeleaf:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 150M
          limits:
            cpu: 200m
            memory: 300M
      restartPolicy: Always