apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring
  name: spring
  namespace: spring
spec:
  ports:
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring
  sessionAffinity: None
  type: ClusterIP